name: ventou
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  provider: ^6.1.2
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  local_auth: ^2.3.0
  google_sign_in: ^6.2.2
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.2
  firebase_data_connect: ^0.1.2+5
  image_picker: ^1.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: Farsan
      fonts:
        - asset: fonts/Farsan-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: didactgothic
      fonts:
        - asset: fonts/didactgothic-regular.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Medium.otf
        - asset: fonts/Dosis-Regular.otf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
