// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-v6sVEoJyVKicVeKWGKd-3XUsDEqIXLs',
    appId: '1:848704699189:web:a9df822e06d229fb186a7c',
    messagingSenderId: '848704699189',
    projectId: 'dashboard-8e414',
    authDomain: 'dashboard-8e414.firebaseapp.com',
    databaseURL: 'https://dashboard-8e414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dashboard-8e414.appspot.com',
    measurementId: 'G-8CHH317T5N',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-v6sVEoJyVKicVeKWGKd-3XUsDEqIXLs',
    appId: '1:848704699189:web:433256d0b45f966b186a7c',
    messagingSenderId: '848704699189',
    projectId: 'dashboard-8e414',
    authDomain: 'dashboard-8e414.firebaseapp.com',
    databaseURL: 'https://dashboard-8e414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dashboard-8e414.appspot.com',
    measurementId: 'G-KBGZC8ESM5',
  );
}
